"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#3b4252)\
$os\
[](bg:#81a1c1 fg:#3b4252)\
$directory\
[](fg:#81a1c1 bg:#2e3440)\
$git_branch\
$git_status\
[](fg:#2e3440 bg:#222730)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:#222730 bg:#191c23)\
$time\
[ ](fg:#191c23)\
\n$character"""

[directory]
style = "fg:#2e3440 bg:#81a1c1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#2e3440"
format = '[[ $symbol $branch ](fg:#81a1c1 bg:#2e3440)]($style)'

[git_status]
style = "bg:#2e3440"
format = '[[($all_status$ahead_behind )](fg:#81a1c1 bg:#2e3440)]($style)'

[nodejs]
symbol = ""
style = "bg:#222730"
format = '[[ $symbol ($version) ](fg:#81a1c1 bg:#222730)]($style)'

[bun]
symbol = ""
style = "bg:#222730"
format = '[[ $symbol ($version) ](fg:#81a1c1 bg:#222730)]($style)'

[rust]
symbol = ""
style = "bg:#222730"
format = '[[ $symbol ($version) ](fg:#81a1c1 bg:#222730)]($style)'

[golang]
symbol = ""
style = "bg:#222730"
format = '[[ $symbol ($version) ](fg:#81a1c1 bg:#222730)]($style)'

[php]
symbol = ""
style = "bg:#222730"
format = '[[ $symbol ($version) ](fg:#81a1c1 bg:#222730)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#191c23"
format = '[[  $time ](fg:#667080 bg:#191c23)]($style)'

[os]
style = "bg:#3b4252 fg:#2e3440"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
